#ifndef MATHS_CONFIG_H
#define MATHS_CONFIG_H

#ifndef MATHS_MAX_PGON_SIZE
#   define MATHS_MAX_PGON_SIZE 32
#endif
#ifndef MATHS_GJK_MAX_ITERATIONS
#   define MATHS_GJK_MAX_ITERATIONS 32
#endif
#ifndef MATHS_EPA_MAX_EDGES
#   define MATHS_EPA_MAX_EDGES 32
#endif

#endif //MATHS_CONFIG_H
